"""empty message

Revision ID: 0ea7f7eb44cc
Revises: 5f20e552fc46
Create Date: 2023-02-28 17:36:50.631841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea7f7eb44cc'
down_revision = '5f20e552fc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paid_sessions')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_sessions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('paid_sessions')

    op.create_table('paid_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sessions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='paid_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='paid_sessions_pkey')
    )
    # ### end Alembic commands ###
