"""empty message

Revision ID: 276e305c926f
Revises: 
Create Date: 2023-02-27 07:46:09.458474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276e305c926f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('start_hour', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('end_hour', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=80), nullable=True),
    sa.Column('allDay', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_post', sa.String(length=100), nullable=False),
    sa.Column('paragraph1', sa.String(), nullable=False),
    sa.Column('paragraph2', sa.String(), nullable=True),
    sa.Column('paragraph3', sa.String(), nullable=True),
    sa.Column('paragraph4', sa.String(), nullable=True),
    sa.Column('paragraph5', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('tags_post', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('problem_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_patient', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('contact')
    op.drop_table('blog_post')
    op.drop_table('appointment')
    # ### end Alembic commands ###
