"""empty message

Revision ID: 3f50e8e19eac
Revises: 3f177922785a
Create Date: 2023-02-16 14:50:45.319715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f50e8e19eac'
down_revision = '3f177922785a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_post', sa.String(length=100), nullable=False),
    sa.Column('body_post', sa.String(), nullable=False),
    sa.Column('tags_post', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post')
    # ### end Alembic commands ###
