"""empty message

Revision ID: 5f20e552fc46
Revises: 17208737dc75
Create Date: 2023-02-28 12:53:46.566126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f20e552fc46'
down_revision = '17208737dc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paid_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paid_sessions')
    # ### end Alembic commands ###
