"""empty message

Revision ID: 647cb5792dd1
Revises: 05fea5e477e0
Create Date: 2023-02-23 18:46:30.645581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647cb5792dd1'
down_revision = '05fea5e477e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_review', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
