"""empty message

Revision ID: 673900164a95
Revises: 647cb5792dd1
Create Date: 2023-02-25 12:43:24.844501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673900164a95'
down_revision = '647cb5792dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
