"""empty message

Revision ID: d41cc156a1c6
Revises: f0e7d299bb2a
Create Date: 2023-02-02 17:26:55.104541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41cc156a1c6'
down_revision = 'f0e7d299bb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requested_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_confirmation', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requested_service', schema=None) as batch_op:
        batch_op.drop_column('pending_confirmation')

    # ### end Alembic commands ###
