"""empty message

Revision ID: f0e7d299bb2a
Revises: f88e813bfe63
Create Date: 2023-02-02 11:13:11.039863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e7d299bb2a'
down_revision = 'f88e813bfe63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.alter_column('contact_person2',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('contact_person2',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
