"""empty message

Revision ID: f88e813bfe63
Revises: 
Create Date: 2023-02-01 08:41:14.655356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88e813bfe63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency', sa.String(length=4), nullable=False),
    sa.Column('subscriber_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('contact_person1', sa.String(length=80), nullable=False),
    sa.Column('contact_person2', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name1', sa.String(length=80), nullable=False),
    sa.Column('last_name2', sa.String(length=80), nullable=False),
    sa.Column('cellphone_number', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('requested_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('requested_date', sa.DateTime(), nullable=False),
    sa.Column('requested_by', sa.String(length=80), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), nullable=False),
    sa.Column('pickup_timetable', sa.String(length=80), nullable=False),
    sa.Column('pickup_company_name', sa.String(length=80), nullable=False),
    sa.Column('pickup_address', sa.String(length=80), nullable=False),
    sa.Column('pickup_contact_person', sa.String(length=80), nullable=False),
    sa.Column('pickup_remarks', sa.String(length=80), nullable=False),
    sa.Column('delivery_company_name', sa.String(length=80), nullable=False),
    sa.Column('delivery_address', sa.String(length=80), nullable=False),
    sa.Column('delivery_contact_person', sa.String(length=80), nullable=False),
    sa.Column('delivery_remarks', sa.String(length=80), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('package_weight', sa.String(length=80), nullable=False),
    sa.Column('package_measures', sa.String(length=80), nullable=False),
    sa.Column('package_amount', sa.String(length=80), nullable=False),
    sa.Column('is_palletized', sa.Boolean(), nullable=False),
    sa.Column('companion_needed', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('requested_service')
    op.drop_table('user')
    op.drop_table('services')
    op.drop_table('roles')
    op.drop_table('client')
    # ### end Alembic commands ###
